version: "3.7"

services:
  opa:
    image: openpolicyagent/opa:0.20.5-rootless
    volumes:
      - ./compose/opa/rules.rego:/tmp/opa/rules.rego:ro
    command:
      - "run"
      - "--server"
      - "--log-level=debug"
      - "--log-format=json-pretty"
      - "--set=decision_logs.console=true"
      - "/tmp/opa"

  openresty:
    build:
      context: .
      dockerfile: ./compose/openresty/Dockerfile
    volumes:
      - ./compose/openresty/conf.d/:/etc/nginx/conf.d:ro
    ports:
      - 80:80
    depends_on:
      - opa
      - whoami

  whoami:
    image: containous/whoami
